mask:
    prefix: "[:"
    suffix: ":]"
    instructions:
      - pattern: "\\d{2}:\\d{2}:\\d{2}"
        mask_with: TIME
      - pattern: "\\b(?:\\d{1,3}\\.){3}\\d{1,3}\\b"
        mask_with: IP
      - pattern: "\\b\\d+\\b"
        mask_with: NUM
drain:
    depth: "4"
    max_children: "1000"
    similarity: "0.4"
